CREATE TABLE `#DB_APPS#_forms` (
   `id` int(10) unsigned not null auto_increment,
   `title` varchar(255),
   `category` varchar(255),
   `header` varchar(255),
   `footer` varchar(255),
   `frmdata` text,
   `engine` varchar(10) default 'auto',
   `layout` varchar(100) not null default 'plain',
   `style` text,
   `script` text,
   `trigger` varchar(255),
   `def_mode` varchar(20) default 'insert',
   `adapter` varchar(255) default 'db',
   `submit_action` varchar(255) default 'reload',
   `submit_table` varchar(255),
   `submit_wherecol` varchar(255),
   `datatable_table` varchar(255),
   `datatable_cols` varchar(1000),
   `datatable_where` varchar(1000),
   `datatable_colnames` varchar(1000),
   `datatable_hiddenCols` varchar(500),
   `datatable_params` varchar(1000),
   `datatable_model` text,
   `blocked` enum('true','false') default 'false',
   `onmenu` enum('true','false') default 'true',
   `privilege` varchar(500) default '*',
   `privilege_model` varchar(2000) default '*',
   `weight` int(11) default '0',
   `hits` int(11) default '0',
   `site` varchar(55) default '*',
   `userid` varchar(255),
   `doc` date,
   `doe` date,
   PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
